services:
  postgres:
    image: postgres:15-alpine
    container_name: autocorrect_postgres
    restart: always
    env_file:
      - .env.${ENV:-local}
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: autocorrect-backend
    container_name: autocorrect_backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.${ENV:-local}
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_DB}?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./backend/migrations:/app/migrations
      - ./images:/app/images  # Volume for storing car images

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    container_name: autocorrect_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.${ENV:-local}
    environment:
      - PORT=3000
    depends_on:
      - backend

volumes:
  postgres_data: