-- Insert challenges data
INSERT INTO challenges (date, image_url, solution_make_id, solution_model_id) VALUES
('2026-02-06', '/images/bmw_e30_m3.jpg', 
    (SELECT id FROM makes WHERE name = 'BMW'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'BMW' AND m.name = '3 Series' AND m.generation = 'E30')),
('2026-02-07', '/images/718_cayman_982.jpg', 
    (SELECT id FROM makes WHERE name = 'Porsche'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '718 Cayman' AND m.generation = '982')),
('2026-02-08', '/images/fd_civic.jpg', 
    (SELECT id FROM makes WHERE name = 'Honda'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Honda' AND m.name = 'Civic' AND m.generation = 'FD')),
('2026-02-09', '/images/370z_z34.jpg', 
    (SELECT id FROM makes WHERE name = 'Nissan'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Nissan' AND m.name = '370Z' AND m.generation = 'Z34')),
('2026-02-10', '/images/amg_gt_r_c190.jpg', 
    (SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Mercedes-Benz' AND m.name = 'AMG GT' AND m.generation = 'C190')),
('2026-02-11', '/images/mr2_sw20.jpg', 
    (SELECT id FROM makes WHERE name = 'Toyota'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'MR2' AND m.generation = 'SW20')),
('2026-02-12', '/images/supra_a90.jpg', 
    (SELECT id FROM makes WHERE name = 'Toyota'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A90')),
('2026-02-13', '/images/911_gt3_992.jpg', 
    (SELECT id FROM makes WHERE name = 'Porsche'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '911' AND m.generation = '992')),
('2026-02-14', '/images/gtr_r34_skyline.jpg', 
    (SELECT id FROM makes WHERE name = 'Nissan'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Nissan' AND m.name = 'GT-R' AND m.generation = 'R34')),
('2026-02-15', '/images/supra_mk4.jpg', 
    (SELECT id FROM makes WHERE name = 'Toyota'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A80')),
('2026-02-16', '/images/458_italia.jpg', 
    (SELECT id FROM makes WHERE name = 'Ferrari'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Ferrari' AND m.name = '458 Italia' AND m.generation = '458')),
('2026-02-17', '/images/tt_8s.jpg', 
    (SELECT id FROM makes WHERE name = 'Audi'), 
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Audi' AND m.name = 'TT' AND m.generation = '8S'));
INSERT INTO challenges (date, image_url, solution_make_id, solution_model_id) VALUES
('2026-02-18', '/images/mustang_s550.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2015-2023')),
('2026-02-19', '/images/tesla_model3.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Tesla')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Tesla') AND LOWER(m.name) = LOWER('Model 3') AND m.year_range = '2017-2024')),
('2026-02-20', '/images/benz_c_w204.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Mercedes-Benz')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Mercedes-Benz') AND LOWER(m.name) = LOWER('C-Class') AND m.year_range = '2007-2014')),
('2026-02-21', '/images/mustang_s550.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2015-2023')),
('2026-02-22', '/images/tesla_model3.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Tesla')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Tesla') AND LOWER(m.name) = LOWER('Model 3') AND m.year_range = '2017-2024')),
('2026-02-23', '/images/benz_c_w204.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Mercedes-Benz')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Mercedes-Benz') AND LOWER(m.name) = LOWER('C-Class') AND m.year_range = '2007-2014')),
('2026-02-24', '/images/bmw_m3_g80.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('BMW')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('BMW') AND LOWER(m.name) = LOWER('M3') AND m.year_range = '2021-present')),
('2026-02-25', '/images/mustang_s197.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2005-2009')),
('2026-02-26', '/images/gtr_r35.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Nissan')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Nissan') AND LOWER(m.name) = LOWER('GT-R') AND m.year_range LIKE '%2009%')),
('2026-02-27', '/images/corvette_c8.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Chevrolet')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Chevrolet') AND LOWER(m.name) = LOWER('Corvette') AND m.year_range LIKE '%2020%')),
('2026-02-28', '/images/tucson_nx4.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Hyundai')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Hyundai') AND LOWER(m.name) = LOWER('Tucson') AND m.year_range LIKE '%2021%')),
('2026-03-01', '/images/passat_b8_estate.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Volkswagen')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Volkswagen') AND LOWER(m.name) = LOWER('Passat') AND m.year_range = '2019-2023'));

INSERT INTO challenges (date, image_url, solution_make_id, solution_model_id) VALUES
('2026-03-02', '/images/458_italia.jpg',
    (SELECT id FROM makes WHERE name = 'Ferrari'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Ferrari' AND m.name = '458 Italia' AND m.generation = '458')),
('2026-03-03', '/images/supra_a90.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A90')),
('2026-03-04', '/images/mustang_s197.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2005-2009')),
('2026-03-05', '/images/911_gt3_992.jpg',
    (SELECT id FROM makes WHERE name = 'Porsche'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '911' AND m.generation = '992')),
('2026-03-06', '/images/mustang_s550.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2015-2023')),
('2026-03-07', '/images/mr2_sw20.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'MR2' AND m.generation = 'SW20')),
('2026-03-08', '/images/370z_z34.jpg',
    (SELECT id FROM makes WHERE name = 'Nissan'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Nissan' AND m.name = '370Z' AND m.generation = 'Z34')),
('2026-03-09', '/images/mustang_s197.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2005-2009')),
('2026-03-10', '/images/supra_a90.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A90')),
('2026-03-11', '/images/passat_b8_estate.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Volkswagen')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Volkswagen') AND LOWER(m.name) = LOWER('Passat') AND m.year_range = '2019-2023')),
('2026-03-12', '/images/fd_civic.jpg',
    (SELECT id FROM makes WHERE name = 'Honda'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Honda' AND m.name = 'Civic' AND m.generation = 'FD')),
('2026-03-13', '/images/passat_b8_estate.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Volkswagen')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Volkswagen') AND LOWER(m.name) = LOWER('Passat') AND m.year_range = '2019-2023')),
('2026-03-14', '/images/bmw_m3_g80.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('BMW')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('BMW') AND LOWER(m.name) = LOWER('M3') AND m.year_range = '2021-present')),
('2026-03-15', '/images/supra_mk4.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A80')),
('2026-03-16', '/images/bmw_m3_g80.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('BMW')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('BMW') AND LOWER(m.name) = LOWER('M3') AND m.year_range = '2021-present')),
('2026-03-17', '/images/fd_civic.jpg',
    (SELECT id FROM makes WHERE name = 'Honda'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Honda' AND m.name = 'Civic' AND m.generation = 'FD')),
('2026-03-18', '/images/benz_c_w204.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Mercedes-Benz')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Mercedes-Benz') AND LOWER(m.name) = LOWER('C-Class') AND m.year_range = '2007-2014')),
('2026-03-19', '/images/bmw_e30_m3.jpg',
    (SELECT id FROM makes WHERE name = 'BMW'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'BMW' AND m.name = '3 Series' AND m.generation = 'E30')),
('2026-03-20', '/images/tesla_model3.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Tesla')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Tesla') AND LOWER(m.name) = LOWER('Model 3') AND m.year_range = '2017-2024')),
('2026-03-21', '/images/passat_b8_estate.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Volkswagen')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Volkswagen') AND LOWER(m.name) = LOWER('Passat') AND m.year_range = '2019-2023')),
('2026-03-22', '/images/718_cayman_982.jpg',
    (SELECT id FROM makes WHERE name = 'Porsche'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '718 Cayman' AND m.generation = '982')),
('2026-03-23', '/images/tesla_model3.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Tesla')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Tesla') AND LOWER(m.name) = LOWER('Model 3') AND m.year_range = '2017-2024')),
('2026-03-24', '/images/corvette_c8.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Chevrolet')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Chevrolet') AND LOWER(m.name) = LOWER('Corvette') AND m.year_range LIKE '%2020%')),
('2026-03-25', '/images/gtr_r35.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Nissan')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Nissan') AND LOWER(m.name) = LOWER('GT-R') AND m.year_range LIKE '%2009%')),
('2026-03-26', '/images/benz_c_w204.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Mercedes-Benz')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Mercedes-Benz') AND LOWER(m.name) = LOWER('C-Class') AND m.year_range = '2007-2014')),
('2026-03-27', '/images/370z_z34.jpg',
    (SELECT id FROM makes WHERE name = 'Nissan'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Nissan' AND m.name = '370Z' AND m.generation = 'Z34')),
('2026-03-28', '/images/tesla_model3.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Tesla')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Tesla') AND LOWER(m.name) = LOWER('Model 3') AND m.year_range = '2017-2024')),
('2026-03-29', '/images/mr2_sw20.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'MR2' AND m.generation = 'SW20')),
('2026-03-30', '/images/fd_civic.jpg',
    (SELECT id FROM makes WHERE name = 'Honda'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Honda' AND m.name = 'Civic' AND m.generation = 'FD')),
('2026-03-31', '/images/718_cayman_982.jpg',
    (SELECT id FROM makes WHERE name = 'Porsche'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '718 Cayman' AND m.generation = '982')),
('2026-04-01', '/images/benz_c_w204.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Mercedes-Benz')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Mercedes-Benz') AND LOWER(m.name) = LOWER('C-Class') AND m.year_range = '2007-2014')),
('2026-04-02', '/images/tucson_nx4.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Hyundai')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Hyundai') AND LOWER(m.name) = LOWER('Tucson') AND m.year_range LIKE '%2021%')),
('2026-04-03', '/images/mustang_s197.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2005-2009')),
('2026-04-04', '/images/718_cayman_982.jpg',
    (SELECT id FROM makes WHERE name = 'Porsche'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '718 Cayman' AND m.generation = '982')),
('2026-04-05', '/images/718_cayman_982.jpg',
    (SELECT id FROM makes WHERE name = 'Porsche'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '718 Cayman' AND m.generation = '982')),
('2026-04-06', '/images/supra_mk4.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A80')),
('2026-04-07', '/images/mustang_s197.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2005-2009')),
('2026-04-08', '/images/supra_a90.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A90')),
('2026-04-09', '/images/supra_a90.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'Supra' AND m.generation = 'A90')),
('2026-04-10', '/images/911_gt3_992.jpg',
    (SELECT id FROM makes WHERE name = 'Porsche'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '911' AND m.generation = '992')),
('2026-04-11', '/images/tesla_model3.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Tesla')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Tesla') AND LOWER(m.name) = LOWER('Model 3') AND m.year_range = '2017-2024')),
('2026-04-12', '/images/mustang_s550.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Ford')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Ford') AND LOWER(m.name) = LOWER('Mustang') AND m.year_range = '2015-2023')),
('2026-04-13', '/images/458_italia.jpg',
    (SELECT id FROM makes WHERE name = 'Ferrari'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Ferrari' AND m.name = '458 Italia' AND m.generation = '458')),
('2026-04-14', '/images/911_gt3_992.jpg',
    (SELECT id FROM makes WHERE name = 'Porsche'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Porsche' AND m.name = '911' AND m.generation = '992')),
('2026-04-15', '/images/mr2_sw20.jpg',
    (SELECT id FROM makes WHERE name = 'Toyota'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Toyota' AND m.name = 'MR2' AND m.generation = 'SW20')),
('2026-04-16', '/images/gtr_r34_skyline.jpg',
    (SELECT id FROM makes WHERE name = 'Nissan'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Nissan' AND m.name = 'GT-R' AND m.generation = 'R34')),
('2026-04-17', '/images/corvette_c8.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Chevrolet')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Chevrolet') AND LOWER(m.name) = LOWER('Corvette') AND m.year_range LIKE '%2020%')),
('2026-04-18', '/images/tt_8s.jpg',
    (SELECT id FROM makes WHERE name = 'Audi'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Audi' AND m.name = 'TT' AND m.generation = '8S')),
('2026-04-19', '/images/fd_civic.jpg',
    (SELECT id FROM makes WHERE name = 'Honda'),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE ma.name = 'Honda' AND m.name = 'Civic' AND m.generation = 'FD')),
('2026-04-20', '/images/gtr_r35.jpg',
    (SELECT id FROM makes WHERE LOWER(name) = LOWER('Nissan')),
    (SELECT m.id FROM models m JOIN makes ma ON m.make_id = ma.id WHERE LOWER(ma.name) = LOWER('Nissan') AND LOWER(m.name) = LOWER('GT-R') AND m.year_range LIKE '%2009%'));
